# Generated by Django 3.1.4 on 2020-12-22 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersmodel',
            options={'verbose_name': 'Список людей'},
        ),
        migrations.RemoveField(
            model_name='usersmodel',
            name='description',
        ),
        migrations.AddField(
            model_name='usersmodel',
            name='age',
            field=models.IntegerField(default=0, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='usersmodel',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterModelTable(
            name='usersmodel',
            table='name_list',
        ),
        migrations.CreateModel(
            name='PetsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Кличка')),
                ('kind', models.CharField(max_length=30, verbose_name='Порода')),
                ('age', models.IntegerField(default=0, verbose_name='Возраст')),
                ('ovner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.usersmodel')),
            ],
        ),
    ]
